# Generated by Django 4.0.5 on 2022-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_prescription_digitzedimagepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='digitzedPdf',
            field=models.FileField(default=1, upload_to='DigitizedPrescription_pdf/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='digitzedImagePdf',
            field=models.FileField(upload_to='DigitizedPrescriptionImage_pdf/'),
        ),
    ]
