# Generated by Django 4.1.3 on 2023-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_prescription_confidence_prescription_nochecked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='fileName',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
    ]
