# Generated by Django 4.1.3 on 2023-01-12 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0010_auto_20230109_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customerUploadedPrescriptions/')),
                ('annotation', models.JSONField(blank=True, null=True)),
                ('medication', models.JSONField(blank=True, null=True)),
                ('phoneNumber', models.IntegerField(default=9937097399)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
